### ISSUE TITLE
The platform is not determined by process.platform statement.

### ISSUE THREAD

**Issue by JeongJun-Lee** [Alex-D/check-disk-space#1]
I am using this module on Electron at Windows 10. At 130 line in index.js, the platform is not determined by process.platform statement because in my case, the variable of process doesn't have platform attribute. So by os module of Node, the platform should be checked by os.platform() === 'win32' in my case.

[index.js]
// Inject the right check depending on the OS
module.exports = (process.platform === 'win32') ? checkWin32 : checkUnix

**Comment by Alex-D** [comment]
Hey!

How it's possible that process.platform is not defined?

https://nodejs.org/api/process.html#process_process_platform

What's the context?

**Comment by JeongJun-Lee** [comment]
![image](https://user-images.githubusercontent.com/11474775/46781665-2b1f3f00-cd3c-11e8-94c6-11114f065ee5.png)

**Comment by Alex-D** [comment]
You should run this module from the main process, not the renderer.

That's a bad way to compute into the renderer process.

https://electronjs.org/docs/tutorial/application-architecture

Hope it helps.
