### ISSUE TITLE
ExecFileException doesn't exist

### ISSUE THREAD

**Issue by jclappiway** [Alex-D/check-disk-space#12]
```
error TS2724: '"child_process"' has no exported member named 'ExecFileException'. Did you mean 'ExecFileOptions'?
import { ExecFileException, ChildProcess } from 'child_process';
            ~~~~~~~~~~~~~~~~~
```

seems like `ExecFileException` became `ExecException`

**Comment by Alex-D** [comment]
Context please? Is that in a new node version or something?

**Comment by jclappiway** [comment]
tested on node 14.x, 16.x

**Comment by Alex-D** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/78e04c781ec2d2d6d5b6d944de4b724b500bfaa9/types/node/child_process.d.ts#L975

Seems to be OK for me ^^

**Comment by jclappiway** [comment]
👌 I updated my "@types/node" to "^16.6.1" it works "14.6.1" was not working. Sorry
