### ISSUE TITLE
WMIC is being deprecated

### ISSUE THREAD

**Issue by jssuttles** [Alex-D/check-disk-space#16]
https://stackoverflow.com/questions/57121875/what-can-i-do-about-wmic-is-deprecated
https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features#:~:text=The%20WMIC%20tool%20is%20deprecated,WMI%20itself%20is%20not%20affected.
https://superuser.com/questions/1546599/has-wmic-been-un-deprecated
The above links indicate that wmic is being deprecated.

**Comment by jssuttles** [comment]
Maybe this should transition to Get-PSDrive: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psdrive?view=powershell-7.2

**Comment by Alex-D** [comment]
Should be fixed as of v3.2.0
