### ISSUE TITLE
PowerShell Pop up a window when run function.

### ISSUE THREAD

**Issue by hughdev** [Alex-D/check-disk-space#19]
// CommonJS
const checkDiskSpace = require('check-disk-space').default

// On Windows
checkDiskSpace('C:/blabla/bla').then((diskSpace) => {
    console.log(diskSpace)
    // {
    //     diskPath: 'C:',
    //     free: 12345678,
    //     size: 98756432
    // }
    // Note: `free` and `size` are in bytes
})
when run this checkDiskSpace function , the PowerShell will Pop up a window on  windows server 2016 datacenter.
can u hlep me how to solve it ,

**Comment by hughdev** [comment]
![image](https://user-images.githubusercontent.com/9314396/167247926-242e9d59-a7ba-4487-94d4-284f188ec7ff.png)
again and again

**Comment by hughdev** [comment]
@Alex-D hello.

**Comment by Alex-D** [comment]
Hi,
The window blink seems due to the use of pkg. I did not found any obvious solution for now.
I continue to search for a fix for that, but that's clearly an edge case ^^

**Comment by Alex-D** [comment]
Seems to be an internal bug of pkg
https://github.com/vercel/pkg/issues/135#issuecomment-1009062110
