### ISSUE TITLE
Wrong output when checking a ZFS pool

### ISSUE THREAD

**Issue by AnixPasBesoin** [Alex-D/check-disk-space#22]
When checking the size of a ZFS pool, `checkDiskSpace('/my-zfs-pool')` is always indicating a 100% disk usage.

Is this a known limitation?

**Comment by Alex-D** [comment]
My code is based on `df`, it seems like DF is wrong about any zfs size :/

**Comment by AnixPasBesoin** [comment]
Actually `df --output=avail,size,target | grep '/my-zfs-pool'` produces the right output (when ran from the cli), I am not sure how it's leveraged here though :)

**Comment by Alex-D** [comment]
Here is the code used on UNIX-like platforms: https://github.com/Alex-D/check-disk-space/blob/d678b42e13facb8bf0803e5b410c78fde4f056ff/src/index.ts#L156-L162

**Comment by Alex-D** [comment]
Please, give me your OS, version, and the output of: `df -Pk -- /my-zfs-pool`

I did not have a ZFS pool setup, and I did not have the time to get one ready.

Then, I will check if I can do anything :)
