### ISSUE TITLE
why use execFileSync to check if support powershell but execFile

### ISSUE THREAD

**Issue by zhoushaokun** [Alex-D/check-disk-space#24]
Related source code is list below:

https://github.com/Alex-D/check-disk-space/blob/d678b42e13facb8bf0803e5b410c78fde4f056ff/src/functions/hasPowerShell3.ts#L17

I cant figure out why not use execFile  which is async and does not block ui（especially in Electron）. 

Appreciate to anyone reply.

**Comment by Alex-D** [comment]
You're right, I should use an async call ^^'

**Comment by Alex-D** [comment]
Now fixed in 3.4.0
