### ISSUE TITLE
Error ！！！！

### ISSUE THREAD

**Issue by NgChiKin** [Alex-D/check-disk-space#26]
error： 
 'Command failed: powershell Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object Caption, FreeSpace, Size\n' +
    'Get-CimInstance :   Ч   \r\n' +
    '    λ     :1  ַ : 1\r\n' +
    '+ Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object Caption, ...\r\n' +
    '+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n' +
    '    + CategoryInfo          : MetadataError: (root\\cimv2:Win32_LogicalDisk:String) [Get-CimInstance], CimException\r\n' +
    '    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand\r\n' +
    ' \r\n'

**Comment by Alex-D** [comment]
Hey
I can't do anything without a procedure to reproduce the error, so I'm sorry.
