### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by BrunnerLivio** [Alex-D/check-disk-space#3]
Hi,

I am using this library for [`@nestjs/terminus`](https://github.com/nestjs/terminus) - a backend TypeScript framework. I would like to offer typing support for this library. I can do the PR myself - but first I wanted to check beforehand whether you agree with my plans.

Thanks a lot, amazing lib! :)

Related nestjs/terminus#233

**Comment by Alex-D** [comment]
I'm open to add a .d file yep :)
